In [4]:
def hello_world():
    print("Hello!")

In [6]:
hello_world()

Hello!


In [7]:
import os

In [10]:
import numpy as np

In [11]:
np.max([1,2,3,4,5])

5

In [13]:
np.mean([1,2,3,4,5])

3.0

In [14]:
np.pi

3.141592653589793

In [15]:
arr = np.array([1,2,3,4,5])

In [16]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr / np.array([5, 4, 3, 2, 1])

array([ 0.2,  0.5,  1. ,  2. ,  5. ])

In [21]:
matrix = np.ones((10,10)) *5

In [22]:
matrix[0][0]

5.0

In [23]:
type(matrix[0][0])

numpy.float64

In [24]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr[(arr< 3)]

array([1, 2])

Pandas and Stuff



In [1]:
import pandas as pd

In [ ]:
pd.read_